IF OBJECT_ID('CHARGE_POSITION') IS NOT NULL
BEGIN
	DROP TABLE CHARGE_POSITION
	PRINT '<< DROPPED TABLE CHARGE_POSITION  >>'
END

CREATE TABLE CHARGE_POSITION
(
	ID_CHARGE_POSITION NUMERIC(12) IDENTITY(1,1) NOT NULL
	,NAME NVARCHAR(255) NOT NULL
	,CONSTRAINT PK_CHARGE_POSITION PRIMARY KEY(ID_CHARGE_POSITION)
)

IF OBJECT_ID('CHARGE_POSITION') IS NOT NULL
BEGIN
	PRINT '<< CREATED TABLE CHARGE_POSITION  >>'
END