IF OBJECT_ID('PERSON_HOUR_VALUE') IS NOT NULL
BEGIN
	DROP TABLE PERSON_HOUR_VALUE
	PRINT '<< CREATED TABLE PERSON_HOUR_VALUE  >>'
END
CREATE TABLE PERSON_HOUR_VALUE
(
	ID_PERSON NUMERIC(12) IDENTITY(1,1) NOT NULL
	,YEAR_MONTH NUMERIC(12) NOT NULL 
	,[VALUE] DECIMAL(18,6) NOT NULL
	,CONSTRAINT PK_PERSON_HOUR_VALUE PRIMARY KEY(ID_PERSON,YEAR_MONTH)
	,CONSTRAINT FK_PERSON_H_REFERENCE_PERSON FOREIGN KEY (ID_PERSON) REFERENCES PERSON(ID_PERSON)
)
IF OBJECT_ID('PERSON_HOUR_VALUE') IS NOT NULL
BEGIN
	PRINT '<< CREATED TABLE PERSON_HOUR_VALUE  >>'
END