IF OBJECT_ID('PERSON') IS NOT NULL
BEGIN
	DROP TABLE PERSON
	PRINT '<< DROPPED TABLE PERSON  >>'
END
CREATE TABLE PERSON
(
	ID_PERSON NUMERIC(12) IDENTITY(1,1) NOT NULL
	,FIRST_NAME NVARCHAR(255) NOT NULL 
	,LAST_NAME NVARCHAR(255) NOT NULL
	,EMAIL NVARCHAR(255) NULL
	,CONSTRAINT PK_PERSON PRIMARY KEY(ID_PERSON)
	
)